#!/usr/bin/env python3

import argparse
import subprocess
import csv
import re
import time

import sys
import os
import tempfile
import shutil
import traceback

import genanki
from model_ex import gen_model
import random
import opera_ex
import ja_es

#output path. dont need to create this file, will be created automatically
if __name__ == '__main__':                                                                                                                                                    
	parser = argparse.ArgumentParser()                                           
	parser.add_argument('--file', help='word list to add to deck', required=True)                                                             
	parser.add_argument('--title', help='name of the deck', required=True)                   
	parser.add_argument('--description', help='Description of the deck.')       
	args = parser.parse_args()

#output_file_path = "output.csv"
newline = "\n"
separator = ","
CWD = os.getcwd()
word_file_path = CWD+"/"+args.file

# import genaki and models

# create deck
deck = genanki.Deck(random.randrange(1 << 30, 1 << 31), args.title)
# set model id, model name
card_model = gen_model('123456789', 'J2S_model_name')

row_index = 0
with open(word_file_path, 'r') as csvfile:
	spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
	for row in spamreader:
		word_now=''
		speech=''
		spanish=''
		misc=''
		audio_now=''
		kanji=''
		kana=''
		furigana=''

		word_now = row[0]
		lookups = ja_es.translate(word_now)
		for piece in lookups:
			#print(piece, '\n')
			kanji = kanji+piece[0]+' '
			speech = speech+piece[1]+' '
			kana = kana+piece[2]+' '
			furigana = furigana + piece[0]+'['+piece[2]+']'+' '
			spanish = spanish+str(piece[3])+' '
			misc = misc+str(piece[4])+' '
			
		'''Pick vocab audio
		try:
			url = 'https://forvo.com/search/'+word_now+'/ja'
			driver.get(url)
			wait = WebDriverWait(driver, 2)
			#element = wait.until(EC.presence_of_all_elements_located((driver.find_elements_by_xpath("//div[@class='list-words']//div[@class='play']")))) 
			element = wait.until(EC.presence_of_all_elements_located((By.XPATH, "//*[contains(@class, 'list-words')]//span[contains(@class, 'play')]")))
			#element = wait.until(EC.presence_of_element_located((By.XPATH, "//*[contains(@class, 'list-words')]//span[contains(@class,'play')]")[0]))
			element[0].click()
			time.sleep(2)
			subprocess.call(['saveaudio'])
		except:
			print('error')

		for af in os.listdir("/home/chewie/Downloads"):
			if af.endswith(".mp3"):
				print(af, " --> ", word_now+".mp3")
				os.rename("/home/chewie/Downloads/"+af, word_now+".mp3")
				audio = word_now+".mp3"
				audio_now = "[sound:"+audio+"]"

		print('\n')         '''

		note = genanki.Note(
				model=card_model,
				fields=[kanji, furigana, speech, spanish, audio_now, misc]
				)
		deck.add_note(note)

genanki.Package(deck).write_to_file(args.title+".apkg")


